### ISSUE TITLE
Help with Coding Proximity Trinkey

### ISSUE THREAD

**Issue by oms900** [adafruit/Adafruit-Proximity-Trinkey-PCB#1]
I am very new to this. Can i program proximity trinkey to either A. Activate a hot key like a spacebar on sensor activation, B.  Act as a digital proximity potentiometer - closer the hand to device, more something is suppressed (pushing down an audio meter as hand approached prox trinkey)? I don't fully understand its capabilities and am just a week in on learning coding. Thanks for any guidance!

**Comment by ladyada** [comment]
hiya for project help please post in the adafruit forums or in the discord chat! thanks :)
